/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * An asset named HLBid
 */
@ApiModel(description = "An asset named HLBid")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-20T16:55:17.138Z")
public class HLBid {
  @SerializedName("$class")
  private String propertyClass = "org.powermatcher.HLBid";

  @SerializedName("BsourceIP")
  private String bsourceIP = null;

  @SerializedName("HLBidNumber")
  private String hlBidNumber = null;

  @SerializedName("Value")
  private List<Double> value = null;

  public HLBid propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return propertyClass
  **/
  @ApiModelProperty(value = "The class identifier for this type")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public HLBid bsourceIP(String bsourceIP) {
    this.bsourceIP = bsourceIP;
    return this;
  }

   /**
   * Get bsourceIP
   * @return bsourceIP
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBsourceIP() {
    return bsourceIP;
  }

  public void setBsourceIP(String bsourceIP) {
    this.bsourceIP = bsourceIP;
  }

  public HLBid hlBidNumber(String hlBidNumber) {
    this.hlBidNumber = hlBidNumber;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return hlBidNumber
  **/
  @ApiModelProperty(required = true, value = "The instance identifier for this type")
  public String getHlBidNumber() {
    return hlBidNumber;
  }

  public void setHlBidNumber(String hlBidNumber) {
    this.hlBidNumber = hlBidNumber;
  }

  public HLBid value(List<Double> value) {
    this.value = value;
    return this;
  }

  public HLBid addValueItem(Double valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<Double>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public List<Double> getValue() {
    return value;
  }

  public void setValue(List<Double> value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HLBid hlBid = (HLBid) o;
    return Objects.equals(this.propertyClass, hlBid.propertyClass) &&
        Objects.equals(this.bsourceIP, hlBid.bsourceIP) &&
        Objects.equals(this.hlBidNumber, hlBid.hlBidNumber) &&
        Objects.equals(this.value, hlBid.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyClass, bsourceIP, hlBidNumber, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HLBid {\n");
    
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    bsourceIP: ").append(toIndentedString(bsourceIP)).append("\n");
    sb.append("    hlBidNumber: ").append(toIndentedString(hlBidNumber)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

