/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A participant named HLDeviceAgent
 */
@ApiModel(description = "A participant named HLDeviceAgent")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-20T16:55:17.138Z")
public class HLDeviceAgent {
  @SerializedName("$class")
  private String propertyClass = "org.powermatcher.HLDeviceAgent";

  @SerializedName("Balance")
  private Double balance = null;

  @SerializedName("AgentID")
  private String agentID = null;

  @SerializedName("AgentName")
  private String agentName = null;

  @SerializedName("AgentIP")
  private String agentIP = null;

  public HLDeviceAgent propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return propertyClass
  **/
  @ApiModelProperty(value = "The class identifier for this type")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public HLDeviceAgent balance(Double balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getBalance() {
    return balance;
  }

  public void setBalance(Double balance) {
    this.balance = balance;
  }

  public HLDeviceAgent agentID(String agentID) {
    this.agentID = agentID;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return agentID
  **/
  @ApiModelProperty(required = true, value = "The instance identifier for this type")
  public String getAgentID() {
    return agentID;
  }

  public void setAgentID(String agentID) {
    this.agentID = agentID;
  }

  public HLDeviceAgent agentName(String agentName) {
    this.agentName = agentName;
    return this;
  }

   /**
   * Get agentName
   * @return agentName
  **/
  @ApiModelProperty(value = "")
  public String getAgentName() {
    return agentName;
  }

  public void setAgentName(String agentName) {
    this.agentName = agentName;
  }

  public HLDeviceAgent agentIP(String agentIP) {
    this.agentIP = agentIP;
    return this;
  }

   /**
   * Get agentIP
   * @return agentIP
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAgentIP() {
    return agentIP;
  }

  public void setAgentIP(String agentIP) {
    this.agentIP = agentIP;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HLDeviceAgent hlDeviceAgent = (HLDeviceAgent) o;
    return Objects.equals(this.propertyClass, hlDeviceAgent.propertyClass) &&
        Objects.equals(this.balance, hlDeviceAgent.balance) &&
        Objects.equals(this.agentID, hlDeviceAgent.agentID) &&
        Objects.equals(this.agentName, hlDeviceAgent.agentName) &&
        Objects.equals(this.agentIP, hlDeviceAgent.agentIP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyClass, balance, agentID, agentName, agentIP);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HLDeviceAgent {\n");
    
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    agentID: ").append(toIndentedString(agentID)).append("\n");
    sb.append("    agentName: ").append(toIndentedString(agentName)).append("\n");
    sb.append("    agentIP: ").append(toIndentedString(agentIP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

