/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * An asset named HLPrice
 */
@ApiModel(description = "An asset named HLPrice")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-20T16:55:17.138Z")
public class HLPrice {
  @SerializedName("$class")
  private String propertyClass = "org.powermatcher.HLPrice";

  @SerializedName("PsourceIP")
  private String psourceIP = null;

  @SerializedName("HLPBidNumber")
  private String hlPBidNumber = null;

  @SerializedName("HLCurrency")
  private String hlCurrency = "PHP";

  @SerializedName("Value")
  private Double value = null;

  public HLPrice propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return propertyClass
  **/
  @ApiModelProperty(value = "The class identifier for this type")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public HLPrice psourceIP(String psourceIP) {
    this.psourceIP = psourceIP;
    return this;
  }

   /**
   * Get psourceIP
   * @return psourceIP
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPsourceIP() {
    return psourceIP;
  }

  public void setPsourceIP(String psourceIP) {
    this.psourceIP = psourceIP;
  }

  public HLPrice hlPBidNumber(String hlPBidNumber) {
    this.hlPBidNumber = hlPBidNumber;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return hlPBidNumber
  **/
  @ApiModelProperty(required = true, value = "The instance identifier for this type")
  public String getHlPBidNumber() {
    return hlPBidNumber;
  }

  public void setHlPBidNumber(String hlPBidNumber) {
    this.hlPBidNumber = hlPBidNumber;
  }

  public HLPrice hlCurrency(String hlCurrency) {
    this.hlCurrency = hlCurrency;
    return this;
  }

   /**
   * Get hlCurrency
   * @return hlCurrency
  **/
  @ApiModelProperty(required = true, value = "")
  public String getHlCurrency() {
    return hlCurrency;
  }

  public void setHlCurrency(String hlCurrency) {
    this.hlCurrency = hlCurrency;
  }

  public HLPrice value(Double value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getValue() {
    return value;
  }

  public void setValue(Double value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HLPrice hlPrice = (HLPrice) o;
    return Objects.equals(this.propertyClass, hlPrice.propertyClass) &&
        Objects.equals(this.psourceIP, hlPrice.psourceIP) &&
        Objects.equals(this.hlPBidNumber, hlPrice.hlPBidNumber) &&
        Objects.equals(this.hlCurrency, hlPrice.hlCurrency) &&
        Objects.equals(this.value, hlPrice.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyClass, psourceIP, hlPBidNumber, hlCurrency, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HLPrice {\n");
    
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    psourceIP: ").append(toIndentedString(psourceIP)).append("\n");
    sb.append("    hlPBidNumber: ").append(toIndentedString(hlPBidNumber)).append("\n");
    sb.append("    hlCurrency: ").append(toIndentedString(hlCurrency)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

