/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.threeten.bp.OffsetDateTime;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A transaction named HLUpdateBid
 */
@ApiModel(description = "A transaction named HLUpdateBid")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-20T16:55:17.138Z")
public class HLUpdateBid {
  @SerializedName("$class")
  private String propertyClass = "org.powermatcher.HLUpdateBid";

  @SerializedName("IPUpdate")
  private String ipUpdate = null;

  @SerializedName("insertBid")
  private List<Double> insertBid = null;

  @SerializedName("currentBid")
  private XAny currentBid = null;

  @SerializedName("transactionId")
  private String transactionId = null;

  @SerializedName("timestamp")
  private OffsetDateTime timestamp = null;

  public HLUpdateBid propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * The class identifier for this type
   * @return propertyClass
  **/
  @ApiModelProperty(value = "The class identifier for this type")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public HLUpdateBid ipUpdate(String ipUpdate) {
    this.ipUpdate = ipUpdate;
    return this;
  }

   /**
   * Get ipUpdate
   * @return ipUpdate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIpUpdate() {
    return ipUpdate;
  }

  public void setIpUpdate(String ipUpdate) {
    this.ipUpdate = ipUpdate;
  }

  public HLUpdateBid insertBid(List<Double> insertBid) {
    this.insertBid = insertBid;
    return this;
  }

  public HLUpdateBid addInsertBidItem(Double insertBidItem) {
    if (this.insertBid == null) {
      this.insertBid = new ArrayList<Double>();
    }
    this.insertBid.add(insertBidItem);
    return this;
  }

   /**
   * Get insertBid
   * @return insertBid
  **/
  @ApiModelProperty(value = "")
  public List<Double> getInsertBid() {
    return insertBid;
  }

  public void setInsertBid(List<Double> insertBid) {
    this.insertBid = insertBid;
  }

  public HLUpdateBid currentBid(XAny currentBid) {
    this.currentBid = currentBid;
    return this;
  }

   /**
   * The identifier of an instance of currentBid
   * @return currentBid
  **/
  @ApiModelProperty(required = true, value = "The identifier of an instance of currentBid")
  public XAny getCurrentBid() {
    return currentBid;
  }

  public void setCurrentBid(XAny currentBid) {
    this.currentBid = currentBid;
  }

  public HLUpdateBid transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * The instance identifier for this type
   * @return transactionId
  **/
  @ApiModelProperty(value = "The instance identifier for this type")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public HLUpdateBid timestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HLUpdateBid hlUpdateBid = (HLUpdateBid) o;
    return Objects.equals(this.propertyClass, hlUpdateBid.propertyClass) &&
        Objects.equals(this.ipUpdate, hlUpdateBid.ipUpdate) &&
        Objects.equals(this.insertBid, hlUpdateBid.insertBid) &&
        Objects.equals(this.currentBid, hlUpdateBid.currentBid) &&
        Objects.equals(this.transactionId, hlUpdateBid.transactionId) &&
        Objects.equals(this.timestamp, hlUpdateBid.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyClass, ipUpdate, insertBid, currentBid, transactionId, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HLUpdateBid {\n");
    
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    ipUpdate: ").append(toIndentedString(ipUpdate)).append("\n");
    sb.append("    insertBid: ").append(toIndentedString(insertBid)).append("\n");
    sb.append("    currentBid: ").append(toIndentedString(currentBid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

