/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package test.io.swagger.client.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.api.HlBidApi;
import io.swagger.client.model.HLBid;
import io.swagger.client.model.InlineResponse200;

/**
 * API tests for HlBidApi
 */
@Ignore
public class HlBidApiTest {

    private final HlBidApi api = new HlBidApi();

    
    /**
     * Create a new instance of the model and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLBidCreateTest() throws ApiException {
        HLBid data = null;
        HLBid response = api.hLBidCreate(data);

        // TODO: test validations
    }
    
    /**
     * Delete a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLBidDeleteByIdTest() throws ApiException {
        String id = null;
        Object response = api.hLBidDeleteById(id);

        // TODO: test validations
    }
    
    /**
     * Check whether a model instance exists in the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLBidExistsTest() throws ApiException {
        String id = null;
        InlineResponse200 response = api.hLBidExists(id);

        // TODO: test validations
    }
    
    /**
     * Find all instances of the model matched by filter from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLBidFindTest() throws ApiException {
        String filter = null;
        List<HLBid> response = api.hLBidFind(filter);

        // TODO: test validations
    }
    
    /**
     * Find a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLBidFindByIdTest() throws ApiException {
        String id = null;
        String filter = null;
        HLBid response = api.hLBidFindById(id, filter);

        // TODO: test validations
    }
    
    /**
     * Replace attributes for a model instance and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLBidReplaceByIdTest() throws ApiException {
        String id = null;
        HLBid data = null;
        HLBid response = api.hLBidReplaceById(id, data);

        // TODO: test validations
    }
    
}
