/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package test.io.swagger.client.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.api.HlDeviceAgentApi;
import io.swagger.client.model.HLDeviceAgent;
import io.swagger.client.model.InlineResponse200;

/**
 * API tests for HlDeviceAgentApi
 */
@Ignore
public class HlDeviceAgentApiTest {

    private final HlDeviceAgentApi api = new HlDeviceAgentApi();

    
    /**
     * Create a new instance of the model and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLDeviceAgentCreateTest() throws ApiException {
        HLDeviceAgent data = null;
        HLDeviceAgent response = api.hLDeviceAgentCreate(data);

        // TODO: test validations
    }
    
    /**
     * Delete a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLDeviceAgentDeleteByIdTest() throws ApiException {
        String id = null;
        Object response = api.hLDeviceAgentDeleteById(id);

        // TODO: test validations
    }
    
    /**
     * Check whether a model instance exists in the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLDeviceAgentExistsTest() throws ApiException {
        String id = null;
        InlineResponse200 response = api.hLDeviceAgentExists(id);

        // TODO: test validations
    }
    
    /**
     * Find all instances of the model matched by filter from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLDeviceAgentFindTest() throws ApiException {
        String filter = null;
        List<HLDeviceAgent> response = api.hLDeviceAgentFind(filter);

        // TODO: test validations
    }
    
    /**
     * Find a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLDeviceAgentFindByIdTest() throws ApiException {
        String id = null;
        String filter = null;
        HLDeviceAgent response = api.hLDeviceAgentFindById(id, filter);

        // TODO: test validations
    }
    
    /**
     * Replace attributes for a model instance and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLDeviceAgentReplaceByIdTest() throws ApiException {
        String id = null;
        HLDeviceAgent data = null;
        HLDeviceAgent response = api.hLDeviceAgentReplaceById(id, data);

        // TODO: test validations
    }
    
}
