/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package test.io.swagger.client.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.api.HlPriceApi;
import io.swagger.client.model.HLPrice;
import io.swagger.client.model.InlineResponse200;

/**
 * API tests for HlPriceApi
 */
@Ignore
public class HlPriceApiTest {

    private final HlPriceApi api = new HlPriceApi();

    
    /**
     * Create a new instance of the model and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLPriceCreateTest() throws ApiException {
        HLPrice data = null;
        HLPrice response = api.hLPriceCreate(data);

        // TODO: test validations
    }
    
    /**
     * Delete a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLPriceDeleteByIdTest() throws ApiException {
        String id = null;
        Object response = api.hLPriceDeleteById(id);

        // TODO: test validations
    }
    
    /**
     * Check whether a model instance exists in the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLPriceExistsTest() throws ApiException {
        String id = null;
        InlineResponse200 response = api.hLPriceExists(id);

        // TODO: test validations
    }
    
    /**
     * Find all instances of the model matched by filter from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLPriceFindTest() throws ApiException {
        String filter = null;
        List<HLPrice> response = api.hLPriceFind(filter);

        // TODO: test validations
    }
    
    /**
     * Find a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLPriceFindByIdTest() throws ApiException {
        String id = null;
        String filter = null;
        HLPrice response = api.hLPriceFindById(id, filter);

        // TODO: test validations
    }
    
    /**
     * Replace attributes for a model instance and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLPriceReplaceByIdTest() throws ApiException {
        String id = null;
        HLPrice data = null;
        HLPrice response = api.hLPriceReplaceById(id, data);

        // TODO: test validations
    }
    
}
