/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package test.io.swagger.client.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.api.HlUpdatePriceApi;
import io.swagger.client.model.HLUpdatePrice;

/**
 * API tests for HlUpdatePriceApi
 */
@Ignore
public class HlUpdatePriceApiTest {

    private final HlUpdatePriceApi api = new HlUpdatePriceApi();

    
    /**
     * Create a new instance of the model and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLUpdatePriceCreateTest() throws ApiException {
        HLUpdatePrice data = null;
        HLUpdatePrice response = api.hLUpdatePriceCreate(data);

        // TODO: test validations
    }
    
    /**
     * Find all instances of the model matched by filter from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLUpdatePriceFindTest() throws ApiException {
        String filter = null;
        List<HLUpdatePrice> response = api.hLUpdatePriceFind(filter);

        // TODO: test validations
    }
    
    /**
     * Find a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hLUpdatePriceFindByIdTest() throws ApiException {
        String id = null;
        String filter = null;
        HLUpdatePrice response = api.hLUpdatePriceFindById(id, filter);

        // TODO: test validations
    }
    
}
