/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package test.io.swagger.client.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.api.ObserverApi;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.Observer;

/**
 * API tests for ObserverApi
 */
@Ignore
public class ObserverApiTest {

    private final ObserverApi api = new ObserverApi();

    
    /**
     * Create a new instance of the model and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void observerCreateTest() throws ApiException {
        Observer data = null;
        Observer response = api.observerCreate(data);

        // TODO: test validations
    }
    
    /**
     * Delete a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void observerDeleteByIdTest() throws ApiException {
        String id = null;
        Object response = api.observerDeleteById(id);

        // TODO: test validations
    }
    
    /**
     * Check whether a model instance exists in the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void observerExistsTest() throws ApiException {
        String id = null;
        InlineResponse200 response = api.observerExists(id);

        // TODO: test validations
    }
    
    /**
     * Find all instances of the model matched by filter from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void observerFindTest() throws ApiException {
        String filter = null;
        List<Observer> response = api.observerFind(filter);

        // TODO: test validations
    }
    
    /**
     * Find a model instance by {{id}} from the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void observerFindByIdTest() throws ApiException {
        String id = null;
        String filter = null;
        Observer response = api.observerFindById(id, filter);

        // TODO: test validations
    }
    
    /**
     * Replace attributes for a model instance and persist it into the data source.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void observerReplaceByIdTest() throws ApiException {
        String id = null;
        Observer data = null;
        Observer response = api.observerReplaceById(id, data);

        // TODO: test validations
    }
    
}
