/*
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package test.io.swagger.client.api;

import java.io.File;
import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import io.swagger.client.ApiException;
import io.swagger.client.api.SystemApi;
import io.swagger.client.model.BindIdentityRequest;
import io.swagger.client.model.IssueIdentityRequest;
import io.swagger.client.model.PingResponse;

/**
 * API tests for SystemApi
 */
@Ignore
public class SystemApiTest {

    private final SystemApi api = new SystemApi();

    
    /**
     * Bind an identity to the specified participant
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemBindIdentityTest() throws ApiException {
        BindIdentityRequest data = null;
        api.systemBindIdentity(data);

        // TODO: test validations
    }
    
    /**
     * Get all Historian Records from the Historian
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemGetAllHistorianRecordsTest() throws ApiException {
        List<Object> response = api.systemGetAllHistorianRecords();

        // TODO: test validations
    }
    
    /**
     * Get all identities from the identity registry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemGetAllIdentitiesTest() throws ApiException {
        List<Object> response = api.systemGetAllIdentities();

        // TODO: test validations
    }
    
    /**
     * Get the specified Historian Record from the Historian
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemGetHistorianRecordByIDTest() throws ApiException {
        String id = null;
        Object response = api.systemGetHistorianRecordByID(id);

        // TODO: test validations
    }
    
    /**
     * Get the specified identity from the identity registry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemGetIdentityByIDTest() throws ApiException {
        String id = null;
        Object response = api.systemGetIdentityByID(id);

        // TODO: test validations
    }
    
    /**
     * Issue an identity to the specified participant
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemIssueIdentityTest() throws ApiException {
        IssueIdentityRequest data = null;
        File response = api.systemIssueIdentity(data);

        // TODO: test validations
    }
    
    /**
     * Test the connection to the business network
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemPingTest() throws ApiException {
        PingResponse response = api.systemPing();

        // TODO: test validations
    }
    
    /**
     * Revoke the specified identity
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void systemRevokeIdentityTest() throws ApiException {
        String id = null;
        api.systemRevokeIdentity(id);

        // TODO: test validations
    }
    
}
